"""Uptodown mirror integration.

Uptodown gates its real APK link behind an interstitial whose download URL is only
generated by the page's own JavaScript. Rather than reverse-engineering that token
scheme, this drives a real (headless) browser through the same click-path a human
would take, then hands the resolved, signed CDN URL off for a plain streamed download.
"""

from typing import Dict, List, Optional, Tuple
from playwright.sync_api import sync_playwright


class UptodownStore:
    """Resolves the current version and real download URL from an Uptodown app page."""

    def get_latest(self, app_page_url: str) -> Tuple[Optional[str], str]:
        """Get the latest version string and a resolved APK download URL.

        Args:
            app_page_url: The app's Uptodown page, e.g. https://doubao.en.uptodown.com/android

        Returns:
            (version, download_url) - version may be None if it couldn't be parsed
        """
        with sync_playwright() as p:
            browser = p.chromium.launch()
            try:
                return self._get_latest_on_browser(browser, app_page_url)
            finally:
                browser.close()

    def get_latest_batch(self, app_page_urls: List[str]) -> Dict[str, Tuple[Optional[str], str]]:
        """Get latest version/download URL for multiple app pages, reusing one browser.

        Args:
            app_page_urls: Uptodown app page URLs to check

        Returns:
            Dict mapping app_page_url -> (version, download_url). A failed lookup's
            value is the raised Exception instead of a tuple.
        """
        results = {}
        with sync_playwright() as p:
            browser = p.chromium.launch()
            try:
                for url in app_page_urls:
                    try:
                        results[url] = self._get_latest_on_browser(browser, url)
                    except Exception as e:
                        results[url] = e
            finally:
                browser.close()
        return results

    def _get_latest_on_browser(self, browser, app_page_url: str) -> Tuple[Optional[str], str]:
        page = browser.new_page()
        try:
            page.goto(app_page_url, wait_until="networkidle", timeout=30000)
            self._dismiss_consent(page)

            version_el = page.query_selector(".version")
            version = version_el.inner_text().strip() if version_el else None

            page.click("#button-download-page-link")
            page.wait_for_load_state("networkidle")
            page.wait_for_timeout(1500)

            with page.expect_download(timeout=45000) as dl_info:
                page.click("#detail-download-button")
            download = dl_info.value
            url = download.url
            # We only need the resolved URL; the actual bytes are fetched
            # separately with a plain streamed request, so cancel the browser's copy.
            download.cancel()

            return version, url
        finally:
            page.close()

    @staticmethod
    def _dismiss_consent(page) -> None:
        """Dismiss the cookie-consent modal if present."""
        try:
            page.get_by_text("ACCEPT ALL", exact=False).first.click(timeout=5000)
        except Exception:
            pass
        page.wait_for_timeout(500)
